from .core import (
    Action,
    Goal,
    GoalSatisfactionVerifier,
    PreconditionsVerifier,
    EffectSupportVerifier,
    Predicate,
    Proposal,
    StateEffect,
    VerificationContext,
    VERIFIER_REGISTRY_NAME,
    VerifierRegistry,
    default_registry,
    evaluate_predicate,
    simulate,
)
from .canonical import canonical_fingerprint, canonical_json
from .capabilities import (
    BUILTIN_VERIFIER_CAPABILITY_REGISTRY,
    VERIFIER_CAPABILITY_FINGERPRINT_FORMAT,
    VERIFIER_CAPABILITY_KIND,
    VERIFIER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT,
    VERIFIER_CAPABILITY_REGISTRY_KIND,
    VERIFIER_CAPABILITY_REGISTRY_SCHEMA_VERSION,
    VERIFIER_CAPABILITY_SCHEMA_VERSION,
    CostClass,
    DeterminismClass,
    UnknownVerifierCapabilityError,
    VerifierCapability,
    VerifierCapabilityError,
    VerifierCapabilityRegistry,
    VerifierCost,
    VerifierDeterminism,
    builtin_verifier_capability_registry,
)
from .dependencies import (
    ClaimDependencyGraph,
    ClaimRecord,
    DependencyCycleError,
    EvidenceRecord,
    UnknownDependencyError,
    evidence_semantic_fingerprint,
    stable_fingerprint,
)
from .bundle import (
    VERIFICATION_BUNDLE_FINGERPRINT_FORMAT,
    VERIFICATION_BUNDLE_KIND,
    VERIFICATION_BUNDLE_SCHEMA_VERSION,
    BundleValidationError,
    VerificationBundle,
    build_verification_bundle,
    validate_verification_bundle,
)
from .ledger import ClaimDefinition, ClaimLedger, ClaimStatus, VerificationSnapshot
from .session import (
    CLAIM_GRAPH_KIND,
    CLAIM_GRAPH_SCHEMA_VERSION,
    COMPOSITE_CLAIM_VERIFIER,
    VERIFICATION_SESSION_KIND,
    VERIFICATION_SESSION_SCHEMA_VERSION,
    AtomicClaim,
    ClaimGraph,
    ClaimGraphValidationError,
    ClaimOperator,
    CompositeClaim,
    SessionBudget,
    SessionClaimState,
    SessionConsumption,
    SessionTermination,
    VerificationSession,
    VerificationSessionError,
    compose_claim_verdict,
)
from .model import (
    Evidence,
    EvidenceState,
    Freshness,
    INDETERMINATE,
    MISSING,
    VerificationIssue,
    VerificationReport,
    VerificationVerdict,
    combine_verdicts,
)
from .adapters.graphify import GraphifyTraversalEvidence, ingest_traversal_result
from .evidence_providers import (
    BUILTIN_EVIDENCE_PROVIDER_CAPABILITY_REGISTRY,
    EVIDENCE_COVERAGE_FINGERPRINT_FORMAT,
    EVIDENCE_COVERAGE_KIND,
    EVIDENCE_COVERAGE_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_CAPABILITY_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_CAPABILITY_KIND,
    EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_KIND,
    EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_CAPABILITY_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_RESULT_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_RESULT_KIND,
    EVIDENCE_PROVIDER_RESULT_SCHEMA_VERSION,
    EVIDENCE_REQUEST_FINGERPRINT_FORMAT,
    EVIDENCE_REQUEST_KIND,
    EVIDENCE_REQUEST_SCHEMA_VERSION,
    EvidenceAcquisitionStatus,
    EvidenceCompleteness,
    EvidenceCoverage,
    EvidenceProvider,
    EvidenceProviderCapability,
    EvidenceProviderCapabilityRegistry,
    EvidenceProviderCompatibility,
    EvidenceProviderError,
    EvidenceProviderIssue,
    EvidenceProviderIssueCategory,
    EvidenceProviderResult,
    EvidenceProviderRuntimeRegistry,
    EvidenceProviderVerifierInput,
    EvidenceRequest,
    UnknownEvidenceProviderError,
    builtin_evidence_provider_capability_registry,
    provider_capability_is_compatible_with_verifier,
    provider_result_for_verifier,
    validate_evidence_provider_request,
    validate_evidence_provider_result,
)
from .regression_test_obligations import (
    BEHAVIOR_EVIDENCE_INVENTORY_FINGERPRINT_FORMAT,
    BEHAVIOR_EVIDENCE_INVENTORY_KIND,
    BEHAVIOR_EVIDENCE_INVENTORY_SCHEMA_VERSION,
    BEHAVIOR_EVIDENCE_KINDS,
    BEHAVIOR_EVIDENCE_KIND_SET,
    DEFAULT_REGRESSION_OBLIGATION_BUDGET,
    EVIDENCE_FACT_CLASS,
    EVIDENCE_KIND_BY_FACT_CLASS,
    OBLIGATION_RULES,
    REGRESSION_OBLIGATION_PLAN_FINGERPRINT_FORMAT,
    REGRESSION_OBLIGATION_PLAN_KIND,
    REGRESSION_OBLIGATION_PLAN_SCHEMA_VERSION,
    REGRESSION_TEST_OBLIGATION_SCHEMA_VERSION,
    REGRESSION_TEST_OBLIGATION_VERIFIER,
    TEST_OBLIGATION_FINGERPRINT_FORMAT,
    TEST_OBLIGATION_GROUNDED,
    TEST_OBLIGATION_KIND,
    BehaviorEvidenceKind,
    BehaviorEvidenceInventory,
    BehaviorFactClass,
    CoverageCompleteness,
    EvidenceInventory,
    FactClassCoverage,
    FactCoverage,
    FactCoverageCompleteness,
    ObligationRule,
    RegressionEvidenceInventory,
    RegressionObligationBudget,
    RegressionObligationConsumption,
    RegressionObligationError,
    RegressionObligationGap,
    RegressionObligationGapCode,
    RegressionObligationPlan,
    RegressionObligationReadiness,
    RegressionObligationTermination,
    TestLevel,
    TestObligation,
    TestObligationKind,
    derive_regression_test_obligations,
    verify_test_obligation,
    verify_test_obligation_bundle,
    verify_test_obligation_grounding,
    verify_test_obligation_grounding_bundle,
)
from .protocol import ProtocolError, handle_request, safe_handle_request
from .text_search import (
    TEXT_SEARCH_VERIFIER,
    TextSearchAssertion,
    TextSearchResult,
    evaluate_text_search,
)
from .verifiers.data_flow import (
    BLOCKING_RESOLUTIONS,
    COMPLETE_COVERAGE,
    DATA_FLOW_VERIFIER,
    SUPPORTED_DATA_FLOW_RELATIONS,
    DataFlowClaim,
    DataFlowClaimKind,
    DataFlowQueryScope,
    build_query_result_evidence,
    verify_data_flow_claim,
    verify_data_flow_claim_bundle,
)
from .wire import SCHEMA_VERSION, decode_markers, envelope

__all__ = [
    "Action", "ClaimDependencyGraph", "ClaimRecord", "DependencyCycleError",
    "ClaimDefinition", "ClaimLedger", "ClaimStatus", "VerificationSnapshot", "Evidence", "EvidenceRecord", "EvidenceState", "Freshness", "Goal",
    "GoalSatisfactionVerifier", "PreconditionsVerifier", "EffectSupportVerifier", "INDETERMINATE", "MISSING", "Predicate",
    "Proposal", "ProtocolError", "handle_request", "safe_handle_request", "SCHEMA_VERSION", "StateEffect", "TextSearchAssertion",
    "TextSearchResult", "UnknownDependencyError", "VerificationContext",
    "VerificationIssue", "VerificationReport", "VerificationVerdict",
    "VerifierRegistry", "combine_verdicts", "decode_markers", "default_registry",
    "envelope", "evaluate_predicate", "evaluate_text_search", "simulate",
    "stable_fingerprint", "evidence_semantic_fingerprint",
    "GraphifyTraversalEvidence", "ingest_traversal_result",
    "BLOCKING_RESOLUTIONS", "COMPLETE_COVERAGE", "DATA_FLOW_VERIFIER",
    "SUPPORTED_DATA_FLOW_RELATIONS", "DataFlowClaim", "DataFlowClaimKind",
    "DataFlowQueryScope", "build_query_result_evidence", "verify_data_flow_claim",
    "verify_data_flow_claim_bundle", "VERIFICATION_BUNDLE_KIND",
    "VERIFICATION_BUNDLE_SCHEMA_VERSION", "VERIFICATION_BUNDLE_FINGERPRINT_FORMAT",
    "BundleValidationError", "VerificationBundle", "build_verification_bundle",
    "validate_verification_bundle", "CLAIM_GRAPH_KIND",
    "CLAIM_GRAPH_SCHEMA_VERSION", "COMPOSITE_CLAIM_VERIFIER",
    "VERIFICATION_SESSION_KIND", "VERIFICATION_SESSION_SCHEMA_VERSION",
    "AtomicClaim", "ClaimGraph", "ClaimGraphValidationError", "ClaimOperator",
    "CompositeClaim", "SessionBudget", "SessionClaimState",
    "SessionConsumption", "SessionTermination", "VerificationSession",
    "VerificationSessionError", "compose_claim_verdict",
    "VERIFIER_REGISTRY_NAME", "TEXT_SEARCH_VERIFIER", "canonical_fingerprint",
    "canonical_json", "VERIFIER_CAPABILITY_SCHEMA_VERSION",
    "VERIFIER_CAPABILITY_KIND", "VERIFIER_CAPABILITY_FINGERPRINT_FORMAT",
    "VERIFIER_CAPABILITY_REGISTRY_SCHEMA_VERSION",
    "VERIFIER_CAPABILITY_REGISTRY_KIND",
    "VERIFIER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT",
    "VerifierDeterminism", "VerifierCost", "VerifierCapability",
    "DeterminismClass", "CostClass",
    "VerifierCapabilityRegistry", "VerifierCapabilityError",
    "UnknownVerifierCapabilityError", "BUILTIN_VERIFIER_CAPABILITY_REGISTRY",
    "builtin_verifier_capability_registry",
    "EVIDENCE_PROVIDER_CAPABILITY_SCHEMA_VERSION",
    "EVIDENCE_PROVIDER_CAPABILITY_KIND",
    "EVIDENCE_PROVIDER_CAPABILITY_FINGERPRINT_FORMAT",
    "EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_SCHEMA_VERSION",
    "EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_KIND",
    "EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT",
    "EVIDENCE_REQUEST_SCHEMA_VERSION", "EVIDENCE_REQUEST_KIND",
    "EVIDENCE_REQUEST_FINGERPRINT_FORMAT", "EVIDENCE_COVERAGE_SCHEMA_VERSION",
    "EVIDENCE_COVERAGE_KIND", "EVIDENCE_COVERAGE_FINGERPRINT_FORMAT",
    "EVIDENCE_PROVIDER_RESULT_SCHEMA_VERSION", "EVIDENCE_PROVIDER_RESULT_KIND",
    "EVIDENCE_PROVIDER_RESULT_FINGERPRINT_FORMAT",
    "EvidenceAcquisitionStatus", "EvidenceCompleteness", "EvidenceCoverage",
    "EvidenceProvider", "EvidenceProviderCapability",
    "EvidenceProviderCapabilityRegistry", "EvidenceProviderRuntimeRegistry",
    "EvidenceProviderCompatibility", "EvidenceProviderError",
    "EvidenceProviderIssue", "EvidenceProviderIssueCategory",
    "EvidenceProviderResult", "EvidenceRequest",
    "EvidenceProviderVerifierInput",
    "UnknownEvidenceProviderError",
    "BUILTIN_EVIDENCE_PROVIDER_CAPABILITY_REGISTRY",
    "builtin_evidence_provider_capability_registry",
    "provider_capability_is_compatible_with_verifier",
    "provider_result_for_verifier",
    "validate_evidence_provider_request",
    "validate_evidence_provider_result",
    "REGRESSION_TEST_OBLIGATION_SCHEMA_VERSION",
    "REGRESSION_TEST_OBLIGATION_VERIFIER", "TEST_OBLIGATION_GROUNDED",
    "BEHAVIOR_EVIDENCE_INVENTORY_SCHEMA_VERSION",
    "BEHAVIOR_EVIDENCE_INVENTORY_KIND",
    "BEHAVIOR_EVIDENCE_INVENTORY_FINGERPRINT_FORMAT",
    "TEST_OBLIGATION_KIND", "TEST_OBLIGATION_FINGERPRINT_FORMAT",
    "REGRESSION_OBLIGATION_PLAN_SCHEMA_VERSION",
    "REGRESSION_OBLIGATION_PLAN_KIND",
    "REGRESSION_OBLIGATION_PLAN_FINGERPRINT_FORMAT",
    "BEHAVIOR_EVIDENCE_KINDS", "BEHAVIOR_EVIDENCE_KIND_SET",
    "BehaviorEvidenceKind", "BehaviorFactClass", "FactCoverageCompleteness",
    "CoverageCompleteness",
    "TestObligationKind", "TestLevel", "RegressionObligationGapCode",
    "RegressionObligationReadiness", "RegressionObligationTermination",
    "EVIDENCE_FACT_CLASS", "EVIDENCE_KIND_BY_FACT_CLASS",
    "RegressionObligationError", "FactClassCoverage", "FactCoverage",
    "BehaviorEvidenceInventory", "EvidenceInventory", "RegressionEvidenceInventory",
    "ObligationRule", "OBLIGATION_RULES", "TestObligation",
    "verify_test_obligation_grounding", "verify_test_obligation_grounding_bundle",
    "verify_test_obligation", "verify_test_obligation_bundle",
    "RegressionObligationBudget", "DEFAULT_REGRESSION_OBLIGATION_BUDGET",
    "RegressionObligationConsumption", "RegressionObligationGap",
    "RegressionObligationPlan", "derive_regression_test_obligations",
]

from .software import Coverage, DeltaKind, FunctionalDeltaItem, FunctionalDeltaResult, FunctionalSnapshot, Observable, RevisionRef, compare_functionality, FUNCTIONAL_REGRESSION_VERIFIER, verify_functional_regression
__all__ += ["Coverage", "DeltaKind", "FunctionalDeltaItem", "FunctionalDeltaResult", "FunctionalSnapshot", "Observable", "RevisionRef", "compare_functionality", "FUNCTIONAL_REGRESSION_VERIFIER", "verify_functional_regression"]
