from .core import (
    Action,
    Goal,
    GoalSatisfactionVerifier,
    PreconditionsVerifier,
    EffectSupportVerifier,
    Predicate,
    Proposal,
    StateEffect,
    VerificationContext,
    VERIFIER_REGISTRY_NAME,
    VerifierRegistry,
    default_registry,
    evaluate_predicate,
    simulate,
)
from .canonical import canonical_fingerprint, canonical_json
from .provider_independence import (
    BUILTIN_PROVIDER_IMPLEMENTATION_REGISTRY,
    PROVIDER_IMPLEMENTATION_REGISTRY_FINGERPRINT_FORMAT,
    IndependenceTrustState,
    ProviderImplementationRegistration,
    ProviderImplementationRegistry,
    ProviderOriginAssertion,
    ProviderTrustContext,
    ValidatedProviderOrigin,
    VerifiedIndependenceFamily,
    builtin_provider_implementation_registry,
)
from .verifiers.corroboration import ProviderVerificationObservation, reconcile_provider_observations
from .code_graph import (
    CODE_GRAPH_OBSERVATION_EVIDENCE_KIND,
    CODE_GRAPH_OBSERVATION_FINGERPRINT_FORMAT,
    CODE_GRAPH_OBSERVATION_KIND,
    CODE_GRAPH_OBSERVATION_SCHEMA_VERSION,
    GRAPH_EVIDENCE_FINGERPRINT_FORMAT,
    GRAPH_MODEL_FINGERPRINT_FORMAT,
    CodeGraphObservationError,
    CodeGraphProviderObservation,
    EvidenceConfidence,
    GraphBlocker,
    GraphEvidence,
    GraphEvidenceKind,
    GraphEvidenceModel,
    GraphEvidenceModelError,
    CoverageCertificate,
    GraphFacts,
    GraphQueryScope,
    ProviderImplementationIdentity,
    SourceRevisionIdentity,
    claim_fingerprint_for_observation,
    decode_code_graph_observation_evidence,
    encode_code_graph_observation_evidence,
    graph_model_from_dict,
)
from .adapters.codeflow import ingest_codeflow_graph, encode_codeflow_code_graph_observation_evidence
from .capabilities import (
    BUILTIN_VERIFIER_CAPABILITY_REGISTRY,
    VERIFIER_CAPABILITY_FINGERPRINT_FORMAT,
    VERIFIER_CAPABILITY_KIND,
    VERIFIER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT,
    VERIFIER_CAPABILITY_REGISTRY_KIND,
    VERIFIER_CAPABILITY_REGISTRY_SCHEMA_VERSION,
    VERIFIER_CAPABILITY_SCHEMA_VERSION,
    CostClass,
    DeterminismClass,
    FalsificationRequirement,
    FalsificationStrategyKind,
    UnknownVerifierCapabilityError,
    VerifierCapability,
    VerifierCapabilityError,
    VerifierCapabilityRegistry,
    VerifierCost,
    VerifierDeterminism,
    builtin_verifier_capability_registry,
)
from .falsification import (
    BUILTIN_FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY,
    COUNTEREXAMPLE_SEARCH_STRATEGY_ID,
    FALSIFICATION_COVERAGE_FINGERPRINT_FORMAT,
    FALSIFICATION_COVERAGE_KIND,
    FALSIFICATION_COVERAGE_SCHEMA_VERSION,
    FALSIFICATION_EXECUTION_INPUT_FINGERPRINT_FORMAT,
    FALSIFICATION_PROBE_FINGERPRINT_FORMAT,
    FALSIFICATION_PROBE_KIND,
    FALSIFICATION_PROBE_SCHEMA_VERSION,
    FALSIFICATION_PROVENANCE_FINGERPRINT_FORMAT,
    FALSIFICATION_PROVENANCE_KIND,
    FALSIFICATION_PROVENANCE_SCHEMA_VERSION,
    FALSIFICATION_RESULT_FINGERPRINT_FORMAT,
    FALSIFICATION_RESULT_KIND,
    FALSIFICATION_RESULT_SCHEMA_VERSION,
    FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT,
    FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY_KIND,
    FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY_SCHEMA_VERSION,
    FALSIFICATION_STRATEGY_DESCRIPTOR_FINGERPRINT_FORMAT,
    FALSIFICATION_STRATEGY_DESCRIPTOR_KIND,
    FALSIFICATION_STRATEGY_DESCRIPTOR_SCHEMA_VERSION,
    FALSIFICATION_STRATEGY_RUNTIME_REGISTRY_FINGERPRINT_FORMAT,
    FALSIFICATION_STRATEGY_RUNTIME_REGISTRY_KIND,
    FALSIFICATION_STRATEGY_RUNTIME_REGISTRY_SCHEMA_VERSION,
    FALSIFICATION_STRATEGY_VERSION,
    FINITE_TEXT_SEQUENCE_INPUT_KIND,
    INDEPENDENT_RECOMPUTE_STRATEGY_ID,
    INVARIANT_CHECK_STRATEGY_ID,
    METAMORPHIC_TRANSFORM_STRATEGY_ID,
    REPRESENTATION_CHECK_STRATEGY_ID,
    WITNESS_SEARCH_STRATEGY_ID,
    DuplicateSemantics,
    FalsificationCompleteness,
    FalsificationCoverage,
    FalsificationDependency,
    FalsificationExecutionInput,
    FalsificationOutcome,
    FalsificationProbe,
    FalsificationProbeOutcome,
    FalsificationProvenance,
    FalsificationResult,
    FalsificationRuntimeRegistry,
    FalsificationStrategyCapabilityRegistry,
    FalsificationStrategyDescriptor,
    FalsificationStrategyError,
    FalsificationStrategyRegistry,
    FalsificationStrategyRuntime,
    FalsificationStrategyRuntimeRegistry,
    FiniteSequencePredicateKind,
    UnknownFalsificationStrategyError,
    builtin_falsification_strategy_capability_registry,
    builtin_falsification_strategy_runtime_registry,
    validate_falsification_result,
)
from .dependencies import (
    ClaimDependencyGraph,
    ClaimRecord,
    DependencyCycleError,
    EvidenceRecord,
    UnknownDependencyError,
    evidence_semantic_fingerprint,
    stable_fingerprint,
)
from .bundle import (
    VERIFICATION_BUNDLE_FINGERPRINT_FORMAT,
    VERIFICATION_BUNDLE_KIND,
    VERIFICATION_BUNDLE_SCHEMA_VERSION,
    BundleValidationError,
    VerificationBundle,
    build_verification_bundle,
    validate_verification_bundle,
)
from .ledger import ClaimDefinition, ClaimLedger, ClaimStatus, VerificationSnapshot
from .session import (
    CLAIM_GRAPH_KIND,
    CLAIM_GRAPH_SCHEMA_VERSION,
    COMPOSITE_CLAIM_VERIFIER,
    VERIFICATION_SESSION_KIND,
    VERIFICATION_SESSION_SCHEMA_VERSION,
    AtomicClaim,
    ClaimGraph,
    ClaimGraphValidationError,
    ClaimOperator,
    CompositeClaim,
    SessionBudget,
    SessionClaimState,
    SessionConsumption,
    SessionTermination,
    VerificationSession,
    VerificationSessionError,
    compose_claim_verdict,
)
from .model import (
    Evidence,
    EvidenceState,
    Freshness,
    INDETERMINATE,
    MISSING,
    VerificationIssue,
    VerificationReport,
    VerificationVerdict,
    combine_verdicts,
)
from .adapters.graphify import GraphifyTraversalEvidence, encode_graphify_code_graph_observation_evidence, ingest_traversal_graph, ingest_traversal_result
from .evidence_providers import (
    AUDIT_OBSERVATION_FINGERPRINT_FORMAT,
    AUDIT_OBSERVATION_KIND,
    AUDIT_OBSERVATION_SCHEMA_VERSION,
    BUILTIN_EVIDENCE_PROVIDER_CAPABILITY_REGISTRY,
    EVIDENCE_COVERAGE_FINGERPRINT_FORMAT,
    EVIDENCE_COVERAGE_KIND,
    EVIDENCE_COVERAGE_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_CAPABILITY_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_CAPABILITY_KIND,
    EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_KIND,
    EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_CAPABILITY_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_RESULT_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_RESULT_KIND,
    EVIDENCE_PROVIDER_RESULT_SCHEMA_VERSION,
    EVIDENCE_PROVIDER_RUNTIME_REGISTRY_FINGERPRINT_FORMAT,
    EVIDENCE_PROVIDER_RUNTIME_REGISTRY_KIND,
    EVIDENCE_PROVIDER_RUNTIME_REGISTRY_SCHEMA_VERSION,
    EVIDENCE_REQUEST_FINGERPRINT_FORMAT,
    EVIDENCE_REQUEST_KIND,
    EVIDENCE_REQUEST_SCHEMA_VERSION,
    EVIDENCE_SLOT_IDENTITY_FINGERPRINT_FORMAT,
    EVIDENCE_SLOT_IDENTITY_KIND,
    EVIDENCE_SLOT_IDENTITY_SCHEMA_VERSION,
    AuditObservation,
    EvidenceAcquisitionStatus,
    EvidenceCompleteness,
    EvidenceCoverage,
    EvidenceProvider,
    EvidenceProviderCapability,
    EvidenceProviderCapabilityRegistry,
    EvidenceProviderCompatibility,
    EvidenceProviderError,
    EvidenceProviderIssue,
    EvidenceProviderIssueCategory,
    EvidenceProviderResult,
    EvidenceProviderRuntimeRegistry,
    EvidenceProviderVerifierInput,
    EvidenceRequest,
    EvidenceSlotIdentity,
    UnknownEvidenceProviderError,
    builtin_evidence_provider_capability_registry,
    provider_capability_is_compatible_with_verifier,
    provider_result_for_verifier,
    validate_evidence_provider_request,
    validate_evidence_provider_result,
)
from .execution import (
    VERIFICATION_EXECUTION_REQUEST_FINGERPRINT_FORMAT,
    VERIFICATION_EXECUTION_REQUEST_KIND,
    VERIFICATION_EXECUTION_REQUEST_SCHEMA_VERSION,
    VERIFICATION_EXECUTION_RESULT_FINGERPRINT_FORMAT,
    VERIFICATION_EXECUTION_RESULT_KIND,
    VERIFICATION_EXECUTION_RESULT_SCHEMA_VERSION,
    VERIFIER_RUNTIME_REGISTRY_FINGERPRINT_FORMAT,
    VERIFIER_RUNTIME_REGISTRY_KIND,
    VERIFIER_RUNTIME_REGISTRY_SCHEMA_VERSION,
    UnknownVerifierRuntimeError,
    VerificationExecutionConsumption,
    VerificationExecutionError,
    VerificationExecutionIssue,
    VerificationExecutionLimits,
    VerificationExecutionRequest,
    VerificationExecutionResult,
    VerificationExecutionStep,
    VerificationExecutionStepStatus,
    VerificationExecutionTermination,
    VerifierDependency,
    VerifierExecutionInput,
    VerifierRuntime,
    VerifierRuntimeRegistry,
    builtin_verifier_runtime_registry,
    execute_verification_plan,
)
from .protocol import ProtocolError, handle_request, safe_handle_request
from .planning import (
    ATOMIC_CLAIM_BINDING_FINGERPRINT_FORMAT,
    ATOMIC_CLAIM_BINDING_KIND,
    ATOMIC_CLAIM_BINDING_SCHEMA_VERSION,
    FALSIFICATION_STRATEGY_BINDING_FINGERPRINT_FORMAT,
    FALSIFICATION_STRATEGY_BINDING_KIND,
    FALSIFICATION_STRATEGY_BINDING_SCHEMA_VERSION,
    VERIFICATION_PLAN_FINGERPRINT_FORMAT,
    VERIFICATION_PLAN_KIND,
    VERIFICATION_PLAN_SCHEMA_VERSION,
    VERIFICATION_PLAN_STEP_FINGERPRINT_FORMAT,
    VERIFICATION_PLANNING_REQUEST_FINGERPRINT_FORMAT,
    VERIFICATION_PLANNING_REQUEST_KIND,
    VERIFICATION_PLANNING_REQUEST_SCHEMA_VERSION,
    AtomicClaimBinding,
    FalsificationStrategyBinding,
    VerificationPlan,
    VerificationPlannerIssue,
    VerificationPlanStep,
    VerificationPlanStepKind,
    VerificationPlanTermination,
    VerificationPlanningBudget,
    VerificationPlanningConsumption,
    VerificationPlanningError,
    VerificationPlanningRequest,
    compile_verification_plan,
)
from .text_search import (
    TEXT_SEARCH_VERIFIER,
    TextSearchAssertion,
    TextSearchResult,
    evaluate_text_search,
)
from .storage import (
    DURABLE_STORAGE_SCHEMA_TABLE,
    DURABLE_STORAGE_SCHEMA_VERSION,
    BundleStore,
    ClaimStore,
    DependencyIndex,
    EvidenceDependency,
    EvidenceSlotVersion,
    EvidenceStore,
    InvalidationEvent,
    SessionExecutionObservation,
    SessionStore,
    StorageConflictError,
    StorageError,
    StorageIntegrityError,
    StorageMigrationError,
    StorageNotFoundError,
    StorageSchemaVersionError,
    StorageUnitOfWork,
    StoredBundle,
    StoredClaimDefinition,
    StoredClaimStatus,
    StoredClaimVersion,
    StoredEvidence,
    StoredFalsificationResult,
    StoredSession,
    StoredTruthError,
    UnitOfWorkFactory,
    persist_execution_result,
)
from .sqlite_storage import (
    SQLiteDurableStorage,
    SQLiteLedgerStorage,
    SQLiteStorage,
    SQLiteUnitOfWork,
)
from .verifiers.code_graph import (
    CODE_GRAPH_VERIFIER,
    CodeGraphClaim,
    CodeGraphClaimKind,
    CodeGraphScope,
    verify_code_graph_claim,
    verify_code_graph_observation,
)
from .verifiers.data_flow import (
    BLOCKING_RESOLUTIONS,
    COMPLETE_COVERAGE,
    DATA_FLOW_VERIFIER,
    SUPPORTED_DATA_FLOW_RELATIONS,
    DataFlowClaim,
    DataFlowClaimKind,
    DataFlowQueryScope,
    SourceRevision,
    CompletenessCertificate,
    build_query_result_evidence,
    verify_data_flow_claim,
    verify_data_flow_claim_bundle,
)
from .wire import SCHEMA_VERSION, decode_markers, envelope

__all__ = [
    "Action", "ClaimDependencyGraph", "ClaimRecord", "DependencyCycleError",
    "ClaimDefinition", "ClaimLedger", "ClaimStatus", "VerificationSnapshot", "Evidence", "EvidenceRecord", "EvidenceState", "Freshness", "Goal",
    "GoalSatisfactionVerifier", "PreconditionsVerifier", "EffectSupportVerifier", "INDETERMINATE", "MISSING", "Predicate",
    "Proposal", "ProtocolError", "handle_request", "safe_handle_request", "SCHEMA_VERSION", "StateEffect", "TextSearchAssertion",
    "TextSearchResult", "UnknownDependencyError", "VerificationContext",
    "VerificationIssue", "VerificationReport", "VerificationVerdict",
    "VerifierRegistry", "combine_verdicts", "decode_markers", "default_registry",
    "envelope", "evaluate_predicate", "evaluate_text_search", "simulate",
    "stable_fingerprint", "evidence_semantic_fingerprint",
    "GraphifyTraversalEvidence", "ingest_traversal_graph", "ingest_traversal_result",
    "encode_graphify_code_graph_observation_evidence",
    "encode_codeflow_code_graph_observation_evidence",
    "CODE_GRAPH_OBSERVATION_EVIDENCE_KIND", "CODE_GRAPH_OBSERVATION_KIND",
    "CODE_GRAPH_OBSERVATION_SCHEMA_VERSION", "CODE_GRAPH_OBSERVATION_FINGERPRINT_FORMAT",
    "CodeGraphObservationError", "CodeGraphProviderObservation",
    "claim_fingerprint_for_observation", "decode_code_graph_observation_evidence",
    "encode_code_graph_observation_evidence", "graph_model_from_dict",
    "CODE_GRAPH_VERIFIER", "CodeGraphClaim", "CodeGraphClaimKind",
    "CodeGraphScope", "verify_code_graph_claim", "verify_code_graph_observation",
    "CoverageCertificate", "GraphFacts", "GraphQueryScope",
    "ProviderImplementationIdentity", "SourceRevisionIdentity",
    "IndependenceTrustState", "VerifiedIndependenceFamily",
    "ProviderImplementationRegistration", "ProviderImplementationRegistry",
    "BUILTIN_PROVIDER_IMPLEMENTATION_REGISTRY",
    "PROVIDER_IMPLEMENTATION_REGISTRY_FINGERPRINT_FORMAT",
    "builtin_provider_implementation_registry",
    "BLOCKING_RESOLUTIONS", "COMPLETE_COVERAGE", "DATA_FLOW_VERIFIER",
    "SUPPORTED_DATA_FLOW_RELATIONS", "DataFlowClaim", "DataFlowClaimKind",
    "DataFlowQueryScope", "SourceRevision", "CompletenessCertificate",
    "build_query_result_evidence", "verify_data_flow_claim",
    "verify_data_flow_claim_bundle", "VERIFICATION_BUNDLE_KIND",
    "VERIFICATION_BUNDLE_SCHEMA_VERSION", "VERIFICATION_BUNDLE_FINGERPRINT_FORMAT",
    "BundleValidationError", "VerificationBundle", "build_verification_bundle",
    "validate_verification_bundle", "CLAIM_GRAPH_KIND",
    "CLAIM_GRAPH_SCHEMA_VERSION", "COMPOSITE_CLAIM_VERIFIER",
    "VERIFICATION_SESSION_KIND", "VERIFICATION_SESSION_SCHEMA_VERSION",
    "AtomicClaim", "ClaimGraph", "ClaimGraphValidationError", "ClaimOperator",
    "CompositeClaim", "SessionBudget", "SessionClaimState",
    "SessionConsumption", "SessionTermination", "VerificationSession",
    "VerificationSessionError", "compose_claim_verdict",
    "VERIFIER_REGISTRY_NAME", "TEXT_SEARCH_VERIFIER", "canonical_fingerprint",
    "canonical_json", "VERIFIER_CAPABILITY_SCHEMA_VERSION",
    "VERIFIER_CAPABILITY_KIND", "VERIFIER_CAPABILITY_FINGERPRINT_FORMAT",
    "VERIFIER_CAPABILITY_REGISTRY_SCHEMA_VERSION",
    "VERIFIER_CAPABILITY_REGISTRY_KIND",
    "VERIFIER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT",
    "VerifierDeterminism", "VerifierCost", "VerifierCapability",
    "FalsificationRequirement", "FalsificationStrategyKind",
    "DeterminismClass", "CostClass",
    "VerifierCapabilityRegistry", "VerifierCapabilityError",
    "UnknownVerifierCapabilityError", "BUILTIN_VERIFIER_CAPABILITY_REGISTRY",
    "builtin_verifier_capability_registry",
    "EVIDENCE_PROVIDER_CAPABILITY_SCHEMA_VERSION",
    "EVIDENCE_PROVIDER_CAPABILITY_KIND",
    "EVIDENCE_PROVIDER_CAPABILITY_FINGERPRINT_FORMAT",
    "EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_SCHEMA_VERSION",
    "EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_KIND",
    "EVIDENCE_PROVIDER_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT",
    "EVIDENCE_REQUEST_SCHEMA_VERSION", "EVIDENCE_REQUEST_KIND",
    "EVIDENCE_REQUEST_FINGERPRINT_FORMAT", "EVIDENCE_COVERAGE_SCHEMA_VERSION",
    "AUDIT_OBSERVATION_SCHEMA_VERSION", "AUDIT_OBSERVATION_KIND",
    "AUDIT_OBSERVATION_FINGERPRINT_FORMAT", "AuditObservation",
    "EVIDENCE_SLOT_IDENTITY_SCHEMA_VERSION", "EVIDENCE_SLOT_IDENTITY_KIND",
    "EVIDENCE_SLOT_IDENTITY_FINGERPRINT_FORMAT", "EvidenceSlotIdentity",
    "EVIDENCE_COVERAGE_KIND", "EVIDENCE_COVERAGE_FINGERPRINT_FORMAT",
    "EVIDENCE_PROVIDER_RESULT_SCHEMA_VERSION", "EVIDENCE_PROVIDER_RESULT_KIND",
    "EVIDENCE_PROVIDER_RESULT_FINGERPRINT_FORMAT",
    "EVIDENCE_PROVIDER_RUNTIME_REGISTRY_SCHEMA_VERSION",
    "EVIDENCE_PROVIDER_RUNTIME_REGISTRY_KIND",
    "EVIDENCE_PROVIDER_RUNTIME_REGISTRY_FINGERPRINT_FORMAT",
    "EvidenceAcquisitionStatus", "EvidenceCompleteness", "EvidenceCoverage",
    "EvidenceProvider", "EvidenceProviderCapability",
    "EvidenceProviderCapabilityRegistry", "EvidenceProviderRuntimeRegistry",
    "EvidenceProviderCompatibility", "EvidenceProviderError",
    "EvidenceProviderIssue", "EvidenceProviderIssueCategory",
    "EvidenceProviderResult", "EvidenceRequest",
    "EvidenceProviderVerifierInput",
    "UnknownEvidenceProviderError",
    "BUILTIN_EVIDENCE_PROVIDER_CAPABILITY_REGISTRY",
    "builtin_evidence_provider_capability_registry",
    "provider_capability_is_compatible_with_verifier",
    "provider_result_for_verifier",
    "validate_evidence_provider_request",
    "validate_evidence_provider_result",
    "ATOMIC_CLAIM_BINDING_SCHEMA_VERSION",
    "ATOMIC_CLAIM_BINDING_KIND",
    "ATOMIC_CLAIM_BINDING_FINGERPRINT_FORMAT",
    "FALSIFICATION_STRATEGY_BINDING_SCHEMA_VERSION",
    "FALSIFICATION_STRATEGY_BINDING_KIND",
    "FALSIFICATION_STRATEGY_BINDING_FINGERPRINT_FORMAT",
    "VERIFICATION_PLANNING_REQUEST_SCHEMA_VERSION",
    "VERIFICATION_PLANNING_REQUEST_KIND",
    "VERIFICATION_PLANNING_REQUEST_FINGERPRINT_FORMAT",
    "VERIFICATION_PLAN_SCHEMA_VERSION", "VERIFICATION_PLAN_KIND",
    "VERIFICATION_PLAN_FINGERPRINT_FORMAT",
    "VERIFICATION_PLAN_STEP_FINGERPRINT_FORMAT", "AtomicClaimBinding",
    "FalsificationStrategyBinding",
    "VerificationPlanningBudget", "VerificationPlanningConsumption",
    "VerificationPlanningError", "VerificationPlanningRequest",
    "VerificationPlannerIssue", "VerificationPlanStep",
    "VerificationPlanStepKind", "VerificationPlanTermination",
    "VerificationPlan", "compile_verification_plan",
    "VERIFIER_RUNTIME_REGISTRY_SCHEMA_VERSION",
    "VERIFIER_RUNTIME_REGISTRY_KIND",
    "VERIFIER_RUNTIME_REGISTRY_FINGERPRINT_FORMAT",
    "VERIFICATION_EXECUTION_REQUEST_SCHEMA_VERSION",
    "VERIFICATION_EXECUTION_REQUEST_KIND",
    "VERIFICATION_EXECUTION_REQUEST_FINGERPRINT_FORMAT",
    "VERIFICATION_EXECUTION_RESULT_SCHEMA_VERSION",
    "VERIFICATION_EXECUTION_RESULT_KIND",
    "VERIFICATION_EXECUTION_RESULT_FINGERPRINT_FORMAT",
    "UnknownVerifierRuntimeError", "VerificationExecutionConsumption",
    "VerificationExecutionError", "VerificationExecutionIssue",
    "VerificationExecutionLimits", "VerificationExecutionRequest",
    "VerificationExecutionResult", "VerificationExecutionStep",
    "VerificationExecutionStepStatus", "VerificationExecutionTermination",
    "VerifierDependency", "VerifierExecutionInput", "VerifierRuntime",
    "VerifierRuntimeRegistry", "builtin_verifier_runtime_registry",
    "execute_verification_plan",
    "WITNESS_SEARCH_STRATEGY_ID", "COUNTEREXAMPLE_SEARCH_STRATEGY_ID",
    "INVARIANT_CHECK_STRATEGY_ID", "METAMORPHIC_TRANSFORM_STRATEGY_ID",
    "INDEPENDENT_RECOMPUTE_STRATEGY_ID", "REPRESENTATION_CHECK_STRATEGY_ID",
    "FALSIFICATION_STRATEGY_VERSION", "FINITE_TEXT_SEQUENCE_INPUT_KIND",
    "BUILTIN_FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY",
    "FALSIFICATION_EXECUTION_INPUT_FINGERPRINT_FORMAT",
    "FALSIFICATION_STRATEGY_DESCRIPTOR_SCHEMA_VERSION",
    "FALSIFICATION_STRATEGY_DESCRIPTOR_KIND",
    "FALSIFICATION_STRATEGY_DESCRIPTOR_FINGERPRINT_FORMAT",
    "FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY_SCHEMA_VERSION",
    "FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY_KIND",
    "FALSIFICATION_STRATEGY_CAPABILITY_REGISTRY_FINGERPRINT_FORMAT",
    "FALSIFICATION_STRATEGY_RUNTIME_REGISTRY_SCHEMA_VERSION",
    "FALSIFICATION_STRATEGY_RUNTIME_REGISTRY_KIND",
    "FALSIFICATION_STRATEGY_RUNTIME_REGISTRY_FINGERPRINT_FORMAT",
    "FALSIFICATION_COVERAGE_SCHEMA_VERSION", "FALSIFICATION_COVERAGE_KIND",
    "FALSIFICATION_COVERAGE_FINGERPRINT_FORMAT",
    "FALSIFICATION_PROVENANCE_SCHEMA_VERSION", "FALSIFICATION_PROVENANCE_KIND",
    "FALSIFICATION_PROVENANCE_FINGERPRINT_FORMAT",
    "FALSIFICATION_PROBE_SCHEMA_VERSION", "FALSIFICATION_PROBE_KIND",
    "FALSIFICATION_PROBE_FINGERPRINT_FORMAT", "FALSIFICATION_RESULT_SCHEMA_VERSION",
    "FALSIFICATION_RESULT_KIND", "FALSIFICATION_RESULT_FINGERPRINT_FORMAT",
    "DuplicateSemantics", "FiniteSequencePredicateKind",
    "FalsificationCompleteness", "FalsificationOutcome",
    "FalsificationProbeOutcome", "FalsificationCoverage",
    "FalsificationProvenance", "FalsificationProbe", "FalsificationResult",
    "FalsificationDependency", "FalsificationExecutionInput",
    "FalsificationStrategyDescriptor", "FalsificationStrategyCapabilityRegistry",
    "FalsificationStrategyRegistry", "FalsificationStrategyRuntime",
    "FalsificationStrategyRuntimeRegistry", "FalsificationRuntimeRegistry",
    "FalsificationStrategyError", "UnknownFalsificationStrategyError",
    "builtin_falsification_strategy_capability_registry",
    "builtin_falsification_strategy_runtime_registry",
    "validate_falsification_result",
    "DURABLE_STORAGE_SCHEMA_TABLE", "DURABLE_STORAGE_SCHEMA_VERSION",
    "EvidenceStore", "BundleStore", "ClaimStore", "SessionStore",
    "DependencyIndex", "StorageUnitOfWork", "UnitOfWorkFactory",
    "StorageError", "StorageNotFoundError", "StorageConflictError",
    "StorageIntegrityError", "StoredTruthError", "StorageSchemaVersionError",
    "StorageMigrationError", "EvidenceDependency", "EvidenceSlotVersion", "StoredEvidence",
    "StoredBundle", "StoredClaimDefinition", "StoredClaimVersion",
    "StoredClaimStatus", "StoredFalsificationResult", "StoredSession",
    "SessionExecutionObservation", "InvalidationEvent", "SQLiteStorage", "SQLiteDurableStorage",
    "SQLiteLedgerStorage", "SQLiteUnitOfWork", "persist_execution_result",
]

from .software import Coverage, DeltaKind, FunctionalDeltaItem, FunctionalDeltaResult, FunctionalSnapshot, Observable, RevisionRef, compare_functionality, FUNCTIONAL_REGRESSION_VERIFIER, verify_functional_regression
__all__ += ["Coverage", "DeltaKind", "FunctionalDeltaItem", "FunctionalDeltaResult", "FunctionalSnapshot", "Observable", "RevisionRef", "compare_functionality", "FUNCTIONAL_REGRESSION_VERIFIER", "verify_functional_regression"]
